# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "447614fa2bf9006c4efc08ce914b7696"
application_url = "https://average-risk-acids-provincial.trycloudflare.com"
embedded = true
name = "app2"
handle = "app2-282"

[build]
include_config_on_deploy = true
dev_store_url = "mytesting-1.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts,write_discounts_allocator_functions, read_products,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_orders,write_orders,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://average-risk-acids-provincial.trycloudflare.com/auth/callback",
  "https://average-risk-acids-provincial.trycloudflare.com/auth/shopify/callback",
  "https://average-risk-acids-provincial.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
