export const europeanTaxRates = {
  AT: { name: "Austria", standardRate: 20 },
  BE: { name: "Belgium", standardRate: 21 },
  BG: { name: "Bulgaria", standardRate: 20 },
  HR: { name: "Croatia", standardRate: 25 },
  CY: { name: "Cyprus", standardRate: 19 },
  CZ: { name: "Czech Republic", standardRate: 21 },
  DK: { name: "Denmark", standardRate: 25 },
  EE: { name: "Estonia", standardRate: 20 },
  FI: { name: "Finland", standardRate: 24 },
  FR: { name: "France", standardRate: 20 },
  DE: { name: "Germany", standardRate: 19 },
  GR: { name: "Greece", standardRate: 24 },
  HU: { name: "Hungary", standardRate: 27 },
  IE: { name: "Ireland", standardRate: 23 },
  IT: { name: "Italy", standardRate: 22 },
  LV: { name: "Latvia", standardRate: 21 },
  LT: { name: "Lithuania", standardRate: 21 },
  LU: { name: "Luxembourg", standardRate: 17 },
  MT: { name: "Malta", standardRate: 18 },
  NL: { name: "Netherlands", standardRate: 21 },
  PL: { name: "Poland", standardRate: 23 },
  PT: { name: "Portugal", standardRate: 23 },
  RO: { name: "Romania", standardRate: 19 },
  SK: { name: "Slovakia", standardRate: 20 },
  SI: { name: "Slovenia", standardRate: 22 },
  ES: { name: "Spain", standardRate: 21 },
  SE: { name: "Sweden", standardRate: 25 },
};
